# Generated by Django 5.1.5 on 2026-03-09 11:18

from django.db import migrations


def mark_existing_verified(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    Profile.objects.all().update(email_verified=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_email_verified'),
    ]

    operations = [
        migrations.RunPython(mark_existing_verified, noop),
    ]
