# Generated by Django 5.1.5 on 2026-03-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_backfill_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='community_slug',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('reply', 'Reply'), ('sphere', 'Sphere')], max_length=20),
        ),
    ]
