"""
Django settings for my_project project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
import dj_database_url

  # Reading from .env file


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "t", "yes", "y", "on"}


SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or 'dev-insecure-secret-key'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', default=False)
ENVIRONMENT = os.environ.get('ENVIRONMENT', 'development')


ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', 'my-project-latest.onrender.com']

SITE_DOMAIN = os.environ.get('SITE_DOMAIN', 'my-project-latest.onrender.com')
SITE_NAME = os.environ.get('SITE_NAME', 'Spherespace')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'storages',
     'cloudinary',
    'cloudinary_storage',
    'corsheaders',
    'crispy_forms',
    'crispy_bootstrap5',
    'crispy_tailwind',
    'rest_framework',
    'drf_spectacular',
    'django_celery_results',
    'users.apps.UsersConfig',
    'blog.apps.BlogConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'payments.apps.PaymentsConfig',
]

# Channels configuration
ASGI_APPLICATION = 'my_project.asgi.application'

# Redis
REDIS_ENABLED = env_bool('REDIS_ENABLED', default=False)
REDIS_URL = os.environ.get('REDIS_URL') or 'redis://127.0.0.1:6379/0'

# Cache/channel layers: use local in-memory defaults unless Redis is explicitly enabled.
if REDIS_ENABLED:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                # Do not break requests if Redis becomes temporarily unavailable.
                'IGNORE_EXCEPTIONS': True,
            },
        },
    }

    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        },
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'local-dev-cache',
        },
    }

    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'my_project.observability.RequestLogMiddleware',
    'users.middleware.AdminIPAllowlistMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'my_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': config('DB_NAME', default=None),
#         'USER': config('DB_USER', default=None),
#         'PASSWORD': config('DB_PASSWORD', default=None),
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3',  # Local fallback
        conn_max_age=600,
        ssl_require=False,  # Set to True only for production PostgreSQL
    )
}

# For production, enable SSL
if os.environ.get('ENVIRONMENT') == 'production':
    DATABASES['default']['OPTIONS'] = {'sslmode': 'require'}

# AWS S3 Configuration
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_REGION_NAME = 'eu-north-1'  # Or use config('AWS_S3_REGION_NAME', default='eu-north-1')
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = 'public-read'  # Choose either 'public-read' or None
AWS_QUERYSTRING_AUTH = False
AWS_S3_VERIFY = True

AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'

# Payments
PAYSTACK_VERIFY = env_bool('PAYSTACK_VERIFY', default=not DEBUG)
PAYSTACK_WEBHOOK_VERIFY = env_bool('PAYSTACK_WEBHOOK_VERIFY', default=not DEBUG)

# Admin allowlist (Tailscale IPs)
ADMIN_IP_RESTRICT = env_bool('ADMIN_IP_RESTRICT', default=True)
ADMIN_ALLOWED_IPS = [
    ip.strip()
    for ip in os.environ.get(
        'ADMIN_ALLOWED_IPS',
        '127.0.0.1,::1,100.90.107.100',
    ).split(',')
    if ip.strip()
]

# Celery

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

CELERY_ENABLED = env_bool('CELERY_ENABLED', default=False)
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL') or os.environ.get('REDIS_URL') or 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND') or CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ALWAYS_EAGER = env_bool('CELERY_TASK_ALWAYS_EAGER', default=False)


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]





# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

from dotenv import load_dotenv

# Load environment variables from the .env file
load_dotenv()

# Load .env or .pro.env depending on DJANGO_ENV
# For local dev only
if os.environ.get('DJANGO_ENV') != 'production':
    from dotenv import load_dotenv
    load_dotenv(dotenv_path=os.path.join(BASE_DIR, '.env'))



STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'blog/static']
MEDIA_URL = os.environ.get("MEDIA_URL") or os.environ.get("media_url") or '/media/'

 #'/media/' 
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = os.environ.get(
    "STATICFILES_STORAGE",
    "whitenoise.storage.CompressedManifestStaticFilesStorage",
)
DEFAULT_FILE_STORAGE = os.environ.get(
    "DEFAULT_FILE_STORAGE",
    "django.core.files.storage.FileSystemStorage",
)

# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGIN_REDIRECT_URL = '/'  # Where to redirect after login (React SPA root)
LOGIN_URL = '/login/'               # URL to redirect unauthorized users
LOGOUT_REDIRECT_URL = '/login/'  # Optional: If you want immediate redirect

# Message tags
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'


SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Logging (structured JSON)
LOG_LEVEL = os.environ.get('LOG_LEVEL', 'INFO')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'loggers': {
        'request': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': True,
        },
        'users.api': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}



SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID', ''),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET', ''),
        },
    },
    'github': {
        'SCOPE': [
            'user',
            'user:email',
        ],
        'APP': {
            'client_id': os.environ.get('GITHUB_CLIENT_ID', ''),
            'secret': os.environ.get('GITHUB_CLIENT_SECRET', ''),
        },
    },
}


SOCIALACCOUNT_LOGIN_ON_GET = True

CRISPY_TEMPLATE_PACK = "tailwind"  # ✅ If using Tailwind CSS
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind" # ✅ If using Tailwind CSS and Bootstrap 5

# API / CORS
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    f'https://{SITE_DOMAIN}',
]
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    f'https://{SITE_DOMAIN}',
]

# Cookie settings for cross-origin requests
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False  # Allow JS to read CSRF token
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 1 week (default is 2 weeks)

# Production security settings
if ENVIRONMENT == 'production':
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/min',
        'register': '3/min',
        'password_change': '3/min',
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 6,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Spherespace API',
    'DESCRIPTION': 'Where People Connect — A modern social platform for communities and conversations',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@myproject.com')

# Email address that receives moderation report notifications
REPORT_NOTIFY_EMAIL = os.environ.get('REPORT_NOTIFY_EMAIL', EMAIL_HOST_USER or 'azizjibril559@gmail.com')

# Password reset token expiry (24 hours)
PASSWORD_RESET_TIMEOUT = 86400

# Paystack Configuration
PAYSTACK_SECRET_KEY = os.environ.get('PAYSTACK_SECRET_KEY', 'sk_test_xxxxxxxxxxxxxxxxxxxxx')
PAYSTACK_PUBLIC_KEY = os.environ.get('PAYSTACK_PUBLIC_KEY', 'pk_test_xxxxxxxxxxxxxxxxxxxxx')

# LiveKit Configuration (Audio Spheres)
LIVEKIT_URL = os.environ.get('LIVEKIT_URL', 'ws://localhost:7880')
LIVEKIT_API_KEY = os.environ.get('LIVEKIT_API_KEY', 'devkey')
LIVEKIT_API_SECRET = os.environ.get('LIVEKIT_API_SECRET', '')






from django.db.utils import ProgrammingError, OperationalError
import django
from django.conf import settings

def create_default_site():
    # Only run this code if sites app is installed
    if 'django.contrib.sites' in settings.INSTALLED_APPS:
        from django.contrib.sites.models import Site
        
        # Ensure SITE_ID is set
        if not hasattr(settings, 'SITE_ID'):
            settings.SITE_ID = 1
            
        # Try to create the default site if it doesn't exist
        try:
            Site.objects.get_or_create(
                id=settings.SITE_ID,
                defaults={
                    'domain': settings.SITE_DOMAIN,
                    'name': settings.SITE_NAME,
                }
            )
        except (ProgrammingError, OperationalError):
    
            pass

