# Generated by Django 5.1.5 on 2026-03-07 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_community_post_community_communitymembership_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='category',
            field=models.CharField(choices=[('gaming', 'Gaming'), ('music', 'Music'), ('coding', 'Coding'), ('art', 'Art'), ('cooking', 'Cooking'), ('chat', 'Chat'), ('education', 'Education'), ('other', 'Other')], default='chat', max_length=20),
        ),
        migrations.CreateModel(
            name='LivestreamBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_bans_issued', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='blog.livestream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_bans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('stream', 'user')},
            },
        ),
    ]
