# Generated by Django 5.1.5 on 2026-03-10 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_sphereroom_sphereparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sphereparticipant',
            name='role',
            field=models.CharField(choices=[('conductor', 'Conductor'), ('speaker', 'Speaker'), ('listener', 'Listener')], default='listener', max_length=10),
        ),
        migrations.CreateModel(
            name='SphereJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sphere_requests', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='blog.sphereroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sphere_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('room', 'user')},
            },
        ),
    ]
