# Generated by Django 5.1.5 on 2026-03-10 20:32

from django.db import migrations


def rename_host_to_conductor(apps, schema_editor):
    SphereParticipant = apps.get_model('blog', 'SphereParticipant')
    SphereParticipant.objects.filter(role='host').update(role='conductor')


def rename_conductor_to_host(apps, schema_editor):
    SphereParticipant = apps.get_model('blog', 'SphereParticipant')
    SphereParticipant.objects.filter(role='conductor').update(role='host')


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_sphereparticipant_role_spherejoinrequest'),
    ]

    operations = [
        migrations.RunPython(rename_host_to_conductor, rename_conductor_to_host),
    ]
